// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLuBhpfRtPbVA-4RWvpEjQy3nlbf1_7t8',
    appId: '1:830768959120:web:87be29dc5800dc72bb9215',
    messagingSenderId: '830768959120',
    projectId: 'personaltherapy-e88e2',
    authDomain: 'personaltherapy-e88e2.firebaseapp.com',
    storageBucket: 'personaltherapy-e88e2.firebasestorage.app',
    measurementId: 'G-KNDF59FM8N',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC00KdlT0RrgwH3kYZW1BuTGZ9UJ85J6mc',
    appId: '1:830768959120:ios:35f7fd0931529ff5bb9215',
    messagingSenderId: '830768959120',
    projectId: 'personaltherapy-e88e2',
    storageBucket: 'personaltherapy-e88e2.firebasestorage.app',
    iosClientId: '830768959120-giems1aoep21nap5ampilifmgfoef2aa.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC00KdlT0RrgwH3kYZW1BuTGZ9UJ85J6mc',
    appId: '1:830768959120:ios:35f7fd0931529ff5bb9215',
    messagingSenderId: '830768959120',
    projectId: 'personaltherapy-e88e2',
    storageBucket: 'personaltherapy-e88e2.firebasestorage.app',
    iosClientId: '830768959120-giems1aoep21nap5ampilifmgfoef2aa.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLuBhpfRtPbVA-4RWvpEjQy3nlbf1_7t8',
    appId: '1:830768959120:web:2ebd2693010fd343bb9215',
    messagingSenderId: '830768959120',
    projectId: 'personaltherapy-e88e2',
    authDomain: 'personaltherapy-e88e2.firebaseapp.com',
    storageBucket: 'personaltherapy-e88e2.firebasestorage.app',
    measurementId: 'G-092G3RKE94',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChClggvJAPtdO5FeovVrmrRS9UxmgeZIY',
    appId: '1:830768959120:android:b72fe610bd985923bb9215',
    messagingSenderId: '830768959120',
    projectId: 'personaltherapy-e88e2',
    storageBucket: 'personaltherapy-e88e2.firebasestorage.app',
  );

}